### PR TITLE
Add support for Mach-O Universal binaries

### PR DESCRIPTION
**Pull request by kevinshome**
This PR adds basic support for [Mach-O Universal binaries](https://en.wikipedia.org/wiki/Universal_binary). 

Some code explanations:
- I did use some malloc/free, not sure how you feel about that since I didn't really see it anywhere else in the source
- I added `mach_universal_arch.h.ib` because I could NOT get `mach_arch.h.ib` to include properly. I tried include guards, I tried `#pragma once`, nothing. If you find something I didn't, definitely remove it, it (shouldn't be) necessary at all.
- My C isn't *that* great, there may definitely be a better optimized way to implement this.

### CODE REVIEW

**Comment by kevinshome** [comment]
[Here's how it looks](https://commedesgarcons.s-ul.eu/c4gIBS7w)
[ntfs kext](https://commedesgarcons.s-ul.eu/sa6j1v0o), for testing, if you need

**Comment by ghost** [comment]
amazing work!!

I absolutely did not expect anyone to integrate so well!, I feel shame full watching you recreate the same bodgie structures I have build :,)

I have absolutely no problem with heap allocations, I just always over do it and end up spending all my time fixing memory issues, so stack allocation is preferable for tasks which are not infinetly expandable, but I see no issue with your use

I made your parser use the mach_arches by making the struct static, I thinking of it rn, there should be a header with declaration of structs and seperate headers with the content of the structs, that way we don't need to make static duplicates

also made the last label print with color, there is some condition where it shifts the label count by one it seams, I will need to look into that more later

Regards! <3

**Comment by ghost** [comment]
ps I don't think this should be a seperate branch, as I don't think it will interefere with anything, let me know what you think

**Comment by ghost** [comment]
gave your universal binary parser a declaration of mach_arches, instead of the header, now we don't need to have to static structs see commit 74da804

**Pull request merged**
